### ISSUE TITLE
My feedback on the App Store

### ISSUE THREAD

**Issue by miladg69** [maxchuquimia/quickdraw#2]
Title: 𝔸𝕟 𝕒𝕞𝕒𝕫𝕚𝕟𝕘 𝕥𝕠𝕠𝕝 𝕥𝕙𝕒𝕥 𝕟𝕖𝕖𝕕 𝕝𝕚𝕥𝕥𝕝𝕖 𝕥𝕨𝕖𝕒𝕜𝕚𝕟𝕘

This is a great utility, that I encourage every presenter to try.
However, there are few requests that I believe will make it perfect
1-The option to hide the pop up screen.
2-The ability to make true lines and true curves.
3-Having the little tool icons (at the bottom left of the screen) in two rather than one raw, since part of it end being hidden under the dock.

GREAT job overall, for a very LITTLE price.

**Comment by maxchuquimia** [comment]
Thanks for the feedback! The dock covering the buttons is a major concern... we’ll look into resolving it as soon as possible.

“True lines” are already possible: just hold down SHIFT while drawing a line! True curves might be a little more difficult to implement, we’ll look into it.

**Comment by porteusconf** [comment]
I verified using 1.2.0 (5) that I can do markups inside a magnified portion of screen (via SysPrefs: Accessibility: Zoom).  Also attached is my quick-and-dirty Quick-Draw-tricks.png which mentions that `Edit: Undo (command-z)` lets you erase annotation(s) starting with newest.  
![Uploading Quick-Draw-tricks.png…](Quick-Draw-tricks.png)

**Comment by miladg69** [comment]
Thanks.

**Comment by maxchuquimia** [comment]
Sorry @miladg69 for the delays - I've been reluctant to release an update on the AppStore because I have a feeling Apple will make me remove the screenshot feature :(
Pressing `/` in the next version to hide the info view will remember that it's been hidden on subsequent launches and I have fixed the dock issue, thanks for that!

@porteusconf thanks for the ideas - I've added the shortcuts to  the README.. I thought the InfoView did a good job of explaining shortcuts to the users but I suppose there are some issues with it so if you have any other ideas on how to better communicate them then let me know!

I'll close this issue once Apple have approved the update

**Comment by maxchuquimia** [comment]
Well that was quick, update approved! Cheers again :)
